apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: apolloio
  name: apolloio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apolloio
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
